- name: Deploy Flask Fundraiser App to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Deployment
      command: kubectl apply -f ansible/k8s-deployment.yml

    - name: Apply Service
      command: kubectl apply -f ansible/k8s-service.yml
