apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundraiser-deployment
  labels:
    app: fundraiser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fundraiser
  template:
    metadata:
      labels:
        app: fundraiser
    spec:
      containers:
        - name: fundraiser
          image: fundraiser-app:test
          ports:
            - containerPort: 5000
