name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pytest -v || true

      - name: Build Docker image
        run: |
          docker build -t fundraiser-app:test .

      # Optional: Deploy to Kubernetes (only for Minikube locally or AKS later)
      - name: Simulate Kubernetes Deployment
        run: |
          echo "Kubernetes deployment step placeholder"
          echo "In production, this would run:"
          echo "kubectl apply -f ansible/k8s-deployment.yml"
          echo "kubectl apply -f ansible/k8s-service.yml"
